### ISSUE TITLE
supercell problem

### ISSUE THREAD

**Issue by mlorke** [ifilot/edp#6]
I tried to use edp on a supercell calculation and noticed that apparently 
edp keeps like a small "edge" from the colormap, i.e. if I try to put the 
picture and its replica side by side to "extent" the supercell it does not fit.
Any way around this? Otherwise great work, really helps

**Comment by ifilot** [comment]
Hi mlorke. Thanks for bringing this to my attention. I was not aware of this issue. I would be happy to fix this in the code. Could you help me reproducing this error by perhaps sharing the density file and the exact command you are using?

**Comment by mlorke** [comment]
Unfortunately the vasp density files are rather large, how do I best get it to you?

**Comment by ifilot** [comment]
You could use [WeTransfer](https://wetransfer.com/), which supports files up to 2GB for free. Alternatively, you can also send it to me via a Dropbox link or something similar.

**Comment by mlorke** [comment]
did send just now, could you briefly confirm here wether you got it?

**Comment by ifilot** [comment]
Yes, I got the file. Thanks for sending it. I have also been able to reproduce the problem, as can be seen below. There is indeed some misalignment between two images. (open this message in a browser to see the image).

![tiled_image](https://user-images.githubusercontent.com/1659768/41020438-2b3ab6fa-6963-11e8-97c7-98f04629abbb.png)

I have some ideas what might be wrong and I will look into it. I will keep you informed!

**Comment by mlorke** [comment]
actually I also tried around with i and it looks like a small "border" is missing, i.e. if
you try to align them with a small space in between you can mke the aequipotential lines "fit"
if you get my point

**Comment by ifilot** [comment]
Sorry for the significant delay, but I finally found the time to resolve this issue. The problem was that I was sampling the grid points incorrectly. To explain, have a look at the Figure below. 

![spacing](https://user-images.githubusercontent.com/1659768/44030852-5ce9dfee-9f02-11e8-9360-7746a6ed95d6.png)

In version 1.7.0 and before, the grid points were sampled as can be seen by the red points. The correct way (starting of version 1.8.0) is to sample these as depicted by the green points. The difference is of course relatively small for sufficiently large grid sizes, but it results in incorrectly displaying the edges.

Thanks again for bringing this to my attention!
